"""
app.py — Active Perturbation Lab
---------------------------------
Interactive Streamlit demo for the active learning POC.

Requires active_learning_results.json (generated by generate_site_data.py).
If the JSON is not found, a synthetic demo mode is activated automatically.

Run:
    streamlit run app.py
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import streamlit as st

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Active Perturbation Lab",
    page_icon="🧬",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Colour scheme (matches paper)
# ---------------------------------------------------------------------------

COLOURS = {
    "random":      "#555555",
    "ucb_only":    "#FF9400",
    "ucb_diverse": "#0279EE",
}
LABELS = {
    "random":      "Random",
    "ucb_only":    "UCB only",
    "ucb_diverse": "UCB + Diversity",
}
DASHES = {
    "random":      "dot",
    "ucb_only":    "solid",
    "ucb_diverse": "dash",
}

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

JSON_PATH = Path("active_learning_results.json")


@st.cache_data
def load_data():
    if not JSON_PATH.exists():
        return None
    with open(JSON_PATH) as f:
        return json.load(f)


@st.cache_data
def make_synthetic_data():
    """
    Synthetic demo data that reproduces the paper's reported numbers exactly.
    Used when active_learning_results.json is not present.
    """
    rng = np.random.RandomState(42)
    n_perts = 105
    n_rounds = 18  # 0..17

    # Simulate PCA scatter with two clusters (high- and low-effect)
    high_n = 35
    low_n = n_perts - high_n
    pca_x = np.concatenate([rng.normal(3, 0.8, high_n), rng.normal(-1, 1.2, low_n)])
    pca_y = np.concatenate([rng.normal(2, 0.6, high_n), rng.normal(-0.5, 1.0, low_n)])
    effect_sizes = np.concatenate([rng.uniform(3.0, 8.0, high_n), rng.uniform(0.3, 2.5, low_n)])
    gene_names = [f"GENE{i:03d}" for i in range(n_perts)]

    perturbations = [
        {"id": gene_names[i], "pca_x": round(float(pca_x[i]), 4),
         "pca_y": round(float(pca_y[i]), 4), "effect_size": round(float(effect_sizes[i]), 4)}
        for i in range(n_perts)
    ]

    budgets = np.linspace(9.5, 90.5, n_rounds)

    def make_trajectory(final_val, peak_val=None, peak_at=5, shape="stable"):
        vals = []
        for i, b in enumerate(budgets):
            if shape == "stable":
                v = 0.65 + (final_val - 0.65) * (b / 90)
                v += rng.normal(0, 0.01)
            elif shape == "collapse":
                if i <= peak_at:
                    v = 0.70 + 0.24 * (i / peak_at)
                else:
                    v = peak_val - (peak_val - final_val) * ((i - peak_at) / (n_rounds - peak_at))
                v += rng.normal(0, 0.01)
            elif shape == "rise":
                v = 0.55 + (final_val - 0.55) * (i / (n_rounds - 1)) ** 0.7
                v += rng.normal(0, 0.01)
            vals.append(round(float(np.clip(v, 0.4, 1.0)), 4))
        return vals

    spearman = {
        "random":      make_trajectory(0.99, shape="rise"),
        "ucb_only":    make_trajectory(0.70, peak_val=0.94, peak_at=4, shape="collapse"),
        "ucb_diverse": make_trajectory(0.88, peak_val=0.94, peak_at=5, shape="collapse"),
    }
    deg = {
        "random":      make_trajectory(0.70, shape="rise"),
        "ucb_only":    make_trajectory(0.57, shape="stable"),
        "ucb_diverse": make_trajectory(0.63, shape="stable"),
    }

    # Build synthetic selection sequences
    all_idx = list(range(n_perts))
    high_idx = list(range(high_n))
    low_idx = list(range(high_n, n_perts))

    def make_rounds(strategy):
        rounds = []
        if strategy == "ucb_only":
            # Preferentially selects high-effect indices first
            order = high_idx + rng.permutation(low_idx).tolist()
        elif strategy == "ucb_diverse":
            order = rng.permutation(all_idx).tolist()
            order = sorted(order, key=lambda i: -effect_sizes[i] * 0.7 + rng.uniform(0, 1))
        else:
            order = rng.permutation(all_idx).tolist()

        seed = order[:10]
        step = 5
        for i, b in enumerate(budgets):
            n_obs = min(10 + i * step, n_perts)
            obs = order[:n_obs]
            rounds.append({
                "budget_pct": round(float(b), 2),
                "observed_indices": obs,
                "spearman_r": spearman[strategy][i],
                "deg_recovery": deg[strategy][i],
            })
        return {"seed_indices": seed, "rounds": rounds}

    strategies_data = {s: {"repeats": [make_rounds(s)]} for s in ["random", "ucb_only", "ucb_diverse"]}

    # Selection bias at 50%
    bias = {}
    for s in ["random", "ucb_only", "ucb_diverse"]:
        obs = strategies_data[s]["repeats"][0]["rounds"][8]["observed_indices"]
        bias[s] = {
            "selected_indices": obs,
            "effect_sizes": [round(float(effect_sizes[i]), 4) for i in obs],
        }

    return {
        "metadata": {
            "n_perturbations": n_perts,
            "seed_size": 10,
            "budget_step": 5,
            "n_rounds": 17,
            "n_repeats": 1,
            "beta_ucb": 1.0,
            "beta_div": 1.5,
            "dataset": "Synthetic demo (Norman et al. 2019 numbers reproduced)",
        },
        "perturbations": perturbations,
        "strategies": strategies_data,
        "selection_bias_rep0": bias,
    }


def get_data():
    data = load_data()
    if data is None:
        return make_synthetic_data(), True  # True = synthetic
    return data, False


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def mean_across_repeats(data, strategy, metric):
    """Return (budgets[], mean[], std[]) averaged across all repeats."""
    repeats = data["strategies"][strategy]["repeats"]
    n_rounds = len(repeats[0]["rounds"])
    budgets = [r["budget_pct"] for r in repeats[0]["rounds"]]
    vals = np.array([
        [rep["rounds"][i][metric] for i in range(n_rounds)]
        for rep in repeats
    ])
    return budgets, vals.mean(axis=0).tolist(), vals.std(axis=0).tolist()


# ---------------------------------------------------------------------------
# Page header
# ---------------------------------------------------------------------------

def render_header(is_synthetic):
    st.title("🧬 Active Perturbation Lab")
    st.markdown(
        "**Can adaptive selection reduce the number of CRISPR experiments needed "
        "to map a perturbation landscape?** This demo shows an active learning loop "
        "on the Norman et al. 2019 K562 CRISPR screen (105 single-gene knockouts). "
        "A GP surrogate in PCA latent space selects which perturbations to observe next — "
        "revealing a systematic failure of standard UCB acquisition at high budgets."
    )
    if is_synthetic:
        st.info(
            "**Demo mode** — `active_learning_results.json` not found. "
            "Showing synthetic data that reproduces the paper's key numbers. "
            "Run `python generate_site_data.py` with the Norman et al. h5ad file "
            "to load real simulation results.",
            icon="ℹ️",
        )
    st.divider()


# ---------------------------------------------------------------------------
# Sidebar controls
# ---------------------------------------------------------------------------

def render_sidebar(data):
    meta = data["metadata"]
    with st.sidebar:
        st.header("Controls")

        st.subheader("Acquisition weights")
        st.caption(
            "Score = Effect + β_UCB · σ_GP + β_div · Diversity  \n"
            "*(Diversity-UCB only)*"
        )
        beta_ucb = st.slider("β_UCB (exploitation)", 0.0, 3.0,
                             float(meta.get("beta_ucb", 1.0)), 0.1)
        beta_div = st.slider("β_div (diversity)", 0.0, 3.0,
                             float(meta.get("beta_div", 1.5)), 0.1)

        st.info("💡 To change these weights, you must re-run the `generate_site_data.py` script.")
        st.divider()

    # --- INTERACTIVE CONTROLS ---
        st.caption("Interactive View for PCA latent space")

        st.subheader("Budget")
        max_budget = int(meta.get("n_rounds", 17)) * int(meta.get("budget_step", 5)) \
                     + int(meta.get("seed_size", 10))
        budget_pct = st.slider(
            "Budget used (%)",
            int(meta.get("seed_size", 10)),
            95, 50, 5,
        )

        st.subheader("Strategies to show")
        show_random = st.checkbox("Random", value=True)
        show_ucb = st.checkbox("UCB only", value=True)
        show_div = st.checkbox("UCB + Diversity", value=True)
        active_strategies = [s for s, show in [
            ("random", show_random),
            ("ucb_only", show_ucb),
            ("ucb_diverse", show_div),
        ] if show]

        st.divider()
        st.subheader("Dataset")
        st.caption(meta.get("dataset", "Norman et al. 2019"))
        st.caption(f"**Perturbations:** {meta.get('n_perturbations', 105)}")
        st.caption(f"**Repeats:** {meta.get('n_repeats', 5)}")
        st.caption(f"**Seed size:** {meta.get('seed_size', 10)}")
        st.caption(f"**Budget step:** {meta.get('budget_step', 5)} per round")

    return budget_pct, active_strategies, beta_ucb, beta_div


# ---------------------------------------------------------------------------
# Panel A + B: metric trajectories
# ---------------------------------------------------------------------------

def render_metric_trajectories(data, active_strategies):
    st.subheader("Metric trajectories across budget")
    st.caption(
        "**Left:** Spearman R between predicted and true effect sizes (unobserved perturbations). "
        "**Right:** Fraction of true top-20 DEGs correctly recovered. "
        "Shaded bands = ±1 SD across repeats."
    )

    fig = make_subplots(
        rows=1, cols=2,
        subplot_titles=["A  Effect-size ranking (Spearman R)",
                        "B  Landscape coverage (top-20 DEG recovery)"],
        horizontal_spacing=0.10,
    )

    for strategy in active_strategies:
        budgets, mean_spe, std_spe = mean_across_repeats(data, strategy, "spearman_r")
        _, mean_deg, std_deg = mean_across_repeats(data, strategy, "deg_recovery")
        col = COLOURS[strategy]
        lab = LABELS[strategy]

        mean_spe = np.array(mean_spe)
        std_spe = np.array(std_spe)
        mean_deg = np.array(mean_deg)
        std_deg = np.array(std_deg)

        # Spearman R
        fig.add_trace(go.Scatter(
            x=budgets, y=mean_spe.tolist(),
            name=lab, line=dict(color=col, width=2.5, dash=DASHES[strategy]),
            legendgroup=strategy, showlegend=True,
        ), row=1, col=1)
        fig.add_trace(go.Scatter(
            x=budgets + budgets[::-1],
            y=(mean_spe + std_spe).tolist() + (mean_spe - std_spe).tolist()[::-1],
            fill="toself", fillcolor=col, opacity=0.12,
            line=dict(width=0), showlegend=False, legendgroup=strategy,
            hoverinfo="skip",
        ), row=1, col=1)

        # DEG recovery
        fig.add_trace(go.Scatter(
            x=budgets, y=mean_deg.tolist(),
            name=lab, line=dict(color=col, width=2.5, dash=DASHES[strategy]),
            legendgroup=strategy, showlegend=False,
        ), row=1, col=2)
        fig.add_trace(go.Scatter(
            x=budgets + budgets[::-1],
            y=(mean_deg + std_deg).tolist() + (mean_deg - std_deg).tolist()[::-1],
            fill="toself", fillcolor=col, opacity=0.12,
            line=dict(width=0), showlegend=False, legendgroup=strategy,
            hoverinfo="skip",
        ), row=1, col=2)

    # 30% budget reference line
    for col_idx in [1, 2]:
        fig.add_vline(x=30, line_dash="dot", line_color="#999999",
                      line_width=1, row=1, col=col_idx)

    fig.add_annotation(x=31, y=0.43, text="30% budget", showarrow=False,
                       font=dict(size=11, color="#888888"), xref="x", yref="y")

    fig.update_xaxes(title_text="Experimental budget used (%)", range=[8, 95])
    fig.update_yaxes(title_text="Spearman R", range=[0.38, 1.05], row=1, col=1)
    fig.update_yaxes(title_text="DEG recovery fraction", range=[0.38, 0.78], row=1, col=2)
    fig.update_layout(
        height=400, legend=dict(orientation="h", y=-0.22, x=0.5, xanchor="center"),
        margin=dict(t=50, b=60, l=60, r=20),
        plot_bgcolor="white", paper_bgcolor="rgba(0,0,0,0)",
    )
    fig.update_xaxes(showgrid=True, gridcolor="#eeeeee")
    fig.update_yaxes(showgrid=True, gridcolor="#eeeeee")

    st.plotly_chart(fig, width='stretch')

    # UCB collapse callout
    if "ucb_only" in active_strategies:
        budgets_u, mean_spe_u, _ = mean_across_repeats(data, "ucb_only", "spearman_r")
        idx30 = min(range(len(budgets_u)), key=lambda i: abs(budgets_u[i] - 30))
        idx90 = len(budgets_u) - 1
        peak = round(mean_spe_u[idx30], 3)
        final = round(mean_spe_u[idx90], 3)

        col1, col2, col3 = st.columns(3)
        col1.metric("UCB Spearman R @ 30% budget", peak, help="Peak accuracy before collapse")
        col2.metric("UCB Spearman R @ 90% budget", final,
                    delta=f"{round(final - peak, 3)}", delta_color="inverse",
                    help="After selection bias exhausts high-effect perturbations")
        col3.metric("Drop", f"{round(peak - final, 3)}", delta=None,
                    help="The UCB collapse — low-effect regime left unobserved")


# ---------------------------------------------------------------------------
# Panel C: selection bias
# ---------------------------------------------------------------------------

def render_selection_bias(data, budget_pct, active_strategies):
    st.subheader("Selection bias distribution")
    st.caption(
        f"Effect-size distribution of perturbations selected by each strategy at "
        f"**{budget_pct}% budget** (repeat 0). "
        "UCB preferentially selects high-effect perturbations, leaving the low-effect "
        "regime unobserved — the 'smoking gun' for the Spearman R collapse."
    )

    # Use pre-computed 50% data from JSON for the histogram; adjust label
    bias = data["selection_bias_rep0"]

    fig = go.Figure()
    bins = np.linspace(0, 9, 19)

    for strategy in active_strategies:
        if strategy not in bias:
            continue
        effs = bias[strategy]["effect_sizes"]
        col = COLOURS[strategy]
        lab = LABELS[strategy]

        counts, edges = np.histogram(effs, bins=bins, density=True)
        fig.add_trace(go.Bar(
            x=((edges[:-1] + edges[1:]) / 2).tolist(),
            y=counts.tolist(),
            name=lab,
            marker_color=col,
            opacity=0.55,
            width=float(edges[1] - edges[0]) * 0.85,
        ))

    mean_vals = {s: round(float(np.mean(bias[s]["effect_sizes"])), 2)
                 for s in active_strategies if s in bias}

    fig.update_layout(
        barmode="overlay",
        xaxis_title="Perturbation effect size (L2 distance from control)",
        yaxis_title="Density",
        height=320,
        legend=dict(orientation="h", y=-0.28, x=0.5, xanchor="center"),
        margin=dict(t=20, b=60, l=60, r=20),
        plot_bgcolor="white", paper_bgcolor="rgba(0,0,0,0)",
    )
    fig.update_xaxes(showgrid=True, gridcolor="#eeeeee")
    fig.update_yaxes(showgrid=True, gridcolor="#eeeeee")

    st.plotly_chart(fig, width='stretch')

    if mean_vals:
        st.caption("Mean effect size of selected perturbations at 50% budget: " +
                   "  |  ".join(f"**{LABELS[s]}**: {v}" for s, v in mean_vals.items()))


# ---------------------------------------------------------------------------
# Latent space scatter: the acquisition playground
# ---------------------------------------------------------------------------

def render_latent_space(data, budget_pct, active_strategies):
    st.subheader("PCA latent space — acquisition playground")
    st.caption(
        "Each point is a perturbation, positioned by its first two principal components "
        "of mean expression. Colour = true effect size (gray → coral = low → high). "
        "**Ringed points** = selected by that strategy at the chosen budget. "
        "Watch how UCB clusters in the high-effect corner while Diversity spreads out."
    )

    perts = data["perturbations"]
    df = pd.DataFrame(perts)

    # Find the round closest to the requested budget for each strategy
    def get_observed_at_budget(strategy, target_pct):
        repeats = data["strategies"][strategy]["repeats"]
        rounds = repeats[0]["rounds"]  # use repeat 0
        closest = min(rounds, key=lambda r: abs(r["budget_pct"] - target_pct))
        return set(closest["observed_indices"])

    n_strategies = len(active_strategies)
    if n_strategies == 0:
        st.warning("Select at least one strategy in the sidebar.")
        return

    cols = st.columns(n_strategies)
    for col_ui, strategy in zip(cols, active_strategies):
        observed_set = get_observed_at_budget(strategy, budget_pct)

        df["selected"] = [i in observed_set for i in range(len(df))]
        df["marker_size"] = df["selected"].map({True: 10, False: 6})
        df["alpha"] = df["selected"].map({True: 1.0, False: 0.35})
        df["label"] = df["selected"].map({True: "selected", False: "unobserved"})

        fig = go.Figure()

        # Unobserved — small, muted
        unobs = df[~df["selected"]]
        fig.add_trace(go.Scatter(
            x=unobs["pca_x"], y=unobs["pca_y"],
            mode="markers",
            marker=dict(
                size=6,
                color=unobs["effect_size"],
                colorscale=[[0, "#D3D1C7"], [1, "#D85A30"]],
                cmin=float(df["effect_size"].min()),
                cmax=float(df["effect_size"].max()),
                opacity=0.35,
                line=dict(width=0),
            ),
            text=unobs["id"],
            hovertemplate="%{text}<br>effect size: %{marker.color:.2f}<extra></extra>",
            showlegend=False,
        ))

        # Selected — larger, full opacity, ring
        obs = df[df["selected"]]
        fig.add_trace(go.Scatter(
            x=obs["pca_x"], y=obs["pca_y"],
            mode="markers",
            marker=dict(
                size=11,
                color=obs["effect_size"],
                colorscale=[[0, "#D3D1C7"], [1, "#D85A30"]],
                cmin=float(df["effect_size"].min()),
                cmax=float(df["effect_size"].max()),
                opacity=1.0,
                line=dict(width=2, color=COLOURS[strategy]),
                showscale=True,
                colorbar=dict(
                    title=dict(
                        text="Effect Size",
                        font=dict(size=10) 
                    ),
                    thickness=10,
                    len=0.7,
                    tickfont=dict(size=9),
                ) if strategy == active_strategies[-1] else None,
            ),
            text=obs["id"],
            hovertemplate="%{text}<br>effect size: %{marker.color:.2f}<extra></extra>",
            showlegend=False,
        ))

        n_sel = len(observed_set)
        pct_actual = round(n_sel / len(df) * 100, 1)

        fig.update_layout(
            title=dict(
                text=f"<b>{LABELS[strategy]}</b><br>"
                     f"<span style='font-size:11px;color:#888'>{n_sel} selected ({pct_actual}%)</span>",
                font=dict(size=13),
            ),
            height=340,
            margin=dict(t=60, b=30, l=30, r=10),
            xaxis=dict(title="PC1", showgrid=True, gridcolor="#eeeeee", zeroline=False),
            yaxis=dict(title="PC2", showgrid=True, gridcolor="#eeeeee", zeroline=False),
            plot_bgcolor="white", paper_bgcolor="rgba(0,0,0,0)",
        )
        col_ui.plotly_chart(fig, width='stretch')


# ---------------------------------------------------------------------------
# Research context
# ---------------------------------------------------------------------------

def render_research_context():
    st.divider()
    with st.expander("Research context and next steps", expanded=False):
        st.markdown("""
**The gap this work addresses**

CPA, scGen, and IMPA predict cellular responses to perturbations from *fixed* datasets.
They do not decide which perturbations to measure next. This POC asks the complementary
question: given a budget of experiments, which perturbations should be screened?

**Key finding: UCB collapse**

Standard UCB acquisition - designed for *target discovery* (find the strongest
perturbations fast) - introduces systematic selection bias. It preferentially
selects high-effect perturbations, leaving the low-effect regime unobserved.
By ~30% budget, UCB achieves Spearman R ≈ 0.94 on unseen perturbations.
But as it exhausts the high-effect set, the remaining unobserved perturbations
are dominated by low-effect knockouts that the GP (trained on high-effect data)
extrapolates to poorly - causing Spearman R to collapse to ~0.70 at 90% budget.

**Coverage–exploitation tradeoff**

The right acquisition function depends on the experimental objective:
- *Target discovery*: UCB is appropriate - find the strongest perturbations quickly.
- *Landscape recovery*: diversity is essential - characterise the full effect-size range.

**Next steps**

1. **Model-native uncertainty**: Replace the PCA+GP surrogate with MC dropout or
   deep ensembles on CPA's perturbation embedding layer - the same model that
   predicts also decides what to measure.

2. **SP-FM uncertainty**: The lab's SP-FM (ICLR 2026) conditions the base
   distribution on the perturbation - uncertainty over this base is a natural
   acquisition signal.

3. **Spatial perturbation selection**: Extend to MintFlow - actively select which
   tissue niches to perturb, guided by NicheCompass niche uncertainty.
        """)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    data, is_synthetic = get_data()
    render_header(is_synthetic)

    budget_pct, active_strategies, beta_ucb, beta_div = render_sidebar(data)

    if not active_strategies:
        st.warning("Select at least one strategy in the sidebar.")
        return

    # Section 1: Metric trajectories (Panels A + B)
    render_metric_trajectories(data, active_strategies)

    st.divider()

    # Section 2: Two panels side by side — latent space + bias distribution
    col_left, col_right = st.columns([3, 2])

    with col_left:
        render_latent_space(data, budget_pct, active_strategies)

    with col_right:
        render_selection_bias(data, budget_pct, active_strategies)

    # Section 3: Research context
    render_research_context()

    # Footer
    st.caption(
        "Norman et al. 2019 · K562 CRISPRi screen · 105 single-gene knockouts · "
        "GP surrogate in PCA latent space · "
        "Neha Mungale · MSc AI for Biomedicine, UCL"
    )


if __name__ == "__main__":
    main()
